---
- name: Setup Docker and Deploy Docker Compose
  hosts: localhost
  become: true
  connection: local

  tasks:
    - name: Install Git
      package:
        name: git
        state: present

    - name: Pull KIAUH
      command: git clone https://github.com/dw-0/kiauh.git /home/makerlab/kiauh
  
    - name: Install docker.io package
      package:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Download docker-compose.yml from GitHub Gist
      get_url:
        url: https://raw.githubusercontent.com/iLikeToCode/ansible/refs/heads/main/orcaslicer-web-compose.yaml
        dest: /opt/orca/docker-compose.yml
        mode: "0644"

    - name: Deploy Docker Compose
      command: docker compose up -d
      args:
        chdir: /opt/orca
